### PR TITLE
Added tidal.com

### PR DESCRIPTION
**Pull request by nischay876**
https://tidal.com/
https://listen.tidal.com/track/165813923
https://www.npmjs.com/package/erela.js-tidal

### CODE REVIEW

**Comment by Adivise** [comment]
hmm this is uselful?

**Comment by XeonE52680v3** [comment]
@Adivise uhhhh maybe because this site stream hifi music and use that link can listen a high quality music. But I think you can update it your self because it to easy to update it.

**Comment by nischay876** [comment]
yeah but still 1 more Support Source readme will not look bad and i have tested it fully there is no bug or anything that may crash the bot

**Comment by Adivise** [comment]
I update now!

**Pull request closed without merging**
